name: tribeka
description: Der schnellste und einfachste Weg deine Arbeitsstunden einzutragen.

version: 1.0.3+27

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  flutter_displaymode: ^0.1.1
  html: ^0.14.0+4
  flutter_secure_storage: ^3.3.5
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1
  material_design_icons_flutter: ^4.0.5755
  flutter_offline: ^0.3.0
  url_launcher: ^5.7.10
  package_info: ^0.4.3+2
  flutter_picker: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
  - assets/

  fonts:
  - family: Tribeka
    fonts:
    - asset: fonts/Digital-Serial-ExtraBold-RegularItalic.ttf